config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :mentorship_requests, only: %i[new create index show update destroy] do
    member do
      patch 'accept', to: 'mentorship_requests#accept', as: 'accept_mentorship_request'
      delete 'destroy', to: 'mentorship_requests#destroy', as: 'destroy_mentorship_request'
      patch 'cancel', to: 'mentorship_requests#cancel', as: 'cancel_mentorship_request'

    end
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new', as: 'new_user_session'
    post 'sign_in', to: 'users/sessions#create', as: 'user_session'
    delete 'sign_out', to: 'users/sessions#destroy', as: 'destroy_user_session'
  end

  root to: 'pages#search'
  get '/search', to: 'pages#search', as: 'search'
  get '/profile', to: 'pages#profile'

  get 'users/:id', to: 'users#show', as: 'user'
  get '/matches', to: 'pages#matches', as: 'matches'
  patch '/mentorship_requests/:id/accept', to: 'mentorship_requests#accept', as: 'accept_mentorship_request'
  patch '/mentorship_requests/:id/destroy', to: 'mentorship_requests#destroy', as: 'destroy_mentorship_request'
  patch '/mentorship_requests/:id/cancel', to: 'mentorship_requests#cancel', as: 'cancel_mentorship_request'


  # Updated users resource to include edit and update actions
  resources :users, only: %i[show edit update]

  resources :posts, only: [:new, :create, :edit, :update, :destroy]
  resources :badges, only: [:show]
end

app/models/user.rb
class User < ApplicationRecord
  include ActionView::Helpers::AssetUrlHelper




  USER_DATA_QUERY = 'SELECT * FROM users WHERE email = ?'.freeze

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise authentication_keys: [:student_id]
  devise :omniauthable, omniauth_providers: %i[google_oauth2]

  validates :student_id, presence: true, uniqueness: true
  validates :area_of_study, presence: true
  validates :current_year, presence: true, numericality: { only_integer: true }
  validates :mentor, inclusion: { in: [true, false] }
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :bio, length: { maximum: 500 }
  validate :cannot_be_mentor_if_first_year
  validates :active_mentorships_count, numericality: { greater_than_or_equal_to: 0 }
  validate :allow_blank_name



  has_many :messages
  has_many :sent_requests, class_name: 'MentorshipRequest', foreign_key: 'mentor_id'
  has_many :received_requests, class_name: 'MentorshipRequest', foreign_key: 'mentee_id'
  has_one_attached :photo
  has_many :posts, dependent: :destroy
  has_many :badges



  scope :by_area_of_study, ->(area) { where(area_of_study: area) if area.present? }
  scope :mentors, -> { where(mentor: true) }
  scope :students, -> { where(mentor: false) }

  def self.find_for_authentication(warden_conditions)
    where(student_id: warden_conditions[:student_id]).first
  end

  def default_photo
    if photo.attached?
      Cloudinary::Utils.cloudinary_url(photo.url)
    else
      ActionController::Base.helpers.asset_url('missing-pic.png')
    end
  end

  def mentor?
    mentor
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # If the user doesn't exist, create a new one
    user ||= User.new(
      email: data['email'],
      name: data['name'],
      mentor: false
    )
    user
  end

  def cannot_be_mentor_if_first_year
    return unless mentor? && current_year == 1

    errors.add(:mentor, 'cannot be a mentor if in the first year')
  end


  def has_first_connection?
    Badge.where(user_id: self.id).exists?(name: "1ª Conexão")
  end

  def first_connection_badge
    Badge.first_connection unless has_first_connection?
  end


  def active_mentorships_count
    received_requests.where(status: 'active').count
  end

  def is_mentor_active?
    :active_mentorships_count > 0
  end

  def award_active_mentor_badge
    return unless mentor? && active_mentorships_count > 0

    Badge.create!(
      user_id: self.id,
      name: "Active Mentor",
      image_url: "active_mentor.png"
    )
  end

  def remove_badge(badge_name)
    badges.where(name: badge_name).destroy_all
  end




  def increment_active_mentorships
    @mentorship_request.mentor.increment_counter(:active_mentorships_count, id)
  end

  def decrement_active_mentorships
    @mentorship_request.mentor.decrement_counter(:active_mentorships_count, id)
  end



  private

  def cannot_be_mentor_if_first_year
    return unless mentor? && current_year == 1

    errors.add(:mentor, 'cannot be a mentor if in the first year')
  end
  def allow_blank_name
    if name.blank? && image_url.present?
      errors.add(:name, "can't be blank")
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
# app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # This will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Google') if is_navigational_format?
    else
      mysql_db = ActiveRecord::Base.establish_connection(:mysql).connection
      user_data = mysql_db.exec_query(User::USER_DATA_QUERY, [@user.email]).first

      if user_data
        user_data = user_data.symbolize_keys
        transformed_user_data = {
          student_id: user_data[:student_id],
          area_of_study: user_data[:area_of_study],
          current_year: user_data[:current_year],
          name: user_data[:name],
          mentor: user_data[:current_year] != 1
        }

        @user.update(transformed_user_data)
      else
        redirect_to root_url
      end
    end
  end

  private

  def after_omniauth_failure_path_for(_scope)
    new_user_session_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(:student_id_authenticatable, scope: resource_name)
    if resource
      sign_in_and_redirect(resource)
    else
      # Handle the case where authentication fails
      # For example, you might want to re-render the sign-in form with an error message
      flash.now[:alert] = 'Invalid student ID or password.'
      render :new
    end
  end

  def destroy
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
    @user.reload
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to profile_path, notice: 'Bio was successfully updated.'
    else
      render :edit
    end
  end

   def index
    @users = User.by_area_of_study(params[:area_of_study])
    if params[:tipo_ajuda] == 'Apoio Estudo'
      @users = @users.where(mentor: false)
    end
    @pagy, @users = pagy(User.all, items: 8)
   end


    private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :bio,
      :area_of_study,
      :current_year,
      :mentor,
      :student_id,
      :apoio_estudo,
      :ajuda_social,
      :apoio_bolsas,
      :photo,
      :active_mentorships_count
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= simple_form_for(current_user, url: user_path(current_user), method: :patch) do |f| %>

    <div class="bio-field">
   <div class="x_button">
      <%= link_to profile_path, class: 'x_button' do %>
      <%= f.label :bio %>
        <%= image_tag "close.png", alt: "X", class: "x_button_image_edit" %>
      <% end %>
    </div>
      <%= f.text_area :bio, size: "60x12" %>
    </div>

  <% if current_user.mentor? %>

    <div class='profile-h3-p'>
      <div class="group">
        <h3>Apoio ao Estudo:</h3>
        <%= f.input_field :apoio_estudo, type: :boolean, checked: current_user.apoio_estudo %>
      </div>
      <div class="group">
        <h3>Apoio a Bolsas:</h3>
        <%= f.input_field :apoio_bolsas, type: :checkbox, checked: current_user.apoio_bolsas %>
      </div>
      <div class="group">
        <h3>Ajuda Social:</h3>
        <%= f.input_field :ajuda_social, type: :checkbox, checked: current_user.ajuda_social %>
      </div>
    </div>
  <% end %>

  <div class="photo-field">
    <%= f.input :photo, as: :file %>
  </div>
  <div class="update-bio-button">
    <%= f.submit "Guardar" %>
  </div>
<% end %>

app/views/users/show.html.erb
<% content_for :page_title do %>
  Perfil
<% end %>

<div class="x_button_show">
      <%= link_to search_path, class: 'x_button' do %>
        <%= image_tag "close.png", alt: "X", class: "x_button_image_edit" %>
      <% end %>
    </div>


<div class="profile-page-info-1">
<div class="user_info_container">
  <div class="profile-pic-show" style="background-image: url('<%= @user.default_photo %>')"></div>
<p><%= @user.name %></p>

</div>
</div>

  <div class='profile-h3-boxes'>
    <div class="group">
    </div>
    <div class="group">
      <h3>Area de Estudo:</h3>
      <p><%= @user.area_of_study %></p>
    </div>

    <div class="group">
      <h3>Ano de Curso:</h3>
      <p><%= @user.current_year %>º</p>
    </div>

    <div class="group">
      <h3>Email:</h3>
      <p><%= @user.email %></p>
    </div>

    <div class="group">
      <h3> Bio: </h3>
      <p> <%= @user.bio %> </p>
    </div>
  </div>

<% if @user.mentor? %>


  <div class='profile-h3-boxes'>
    <div class="group">
      <h3>Apoio ao Estudo:</h3>
      <p><%= @user.apoio_estudo ? 'Sim' : 'Não' %></p>
    </div>
    <div class="group">
      <h3>Apoio a Bolsas:</h3>
      <p><%= @user.apoio_bolsas ? 'Sim' : 'Não' %></p>
    </div>
    <div class="group">
      <h3>Apoio Social:</h3>
      <p><%= @user.ajuda_social ? 'Sim' : 'Não' %></p>
    </div>
  </div>

<% end %>


<% if @user.mentor? %>

  <div class="badges">
  <h2 style="text-align: center;">Badges</h2>
<% if @user.badges.any? %>
<div class="badges-content">
  <% @user.badges.each do |badge| %>
    <div class="badges-content-all">

    <%= image_tag(badge.image_url) %> <%= badge.name %>
    </div>
  <% end %>
</div>
<% else %>
  <p>Nenhum badge obtido ainda.</p>
<% end %>
</div>
<% end %>

<% if @user.mentor? %>


  <div class="post-container">

    <h2 id="posts-h1">Posts</h2>
    <% @user.posts.each do |post| %>
      <div class="post">
        <h1><%= post.title %></h1>
  <%= image_tag post.default_image, alt: post.title %>
  <p id="post-date"><%= post.created_at.strftime("%d/%m/%Y") %></p>
        <p><%= post.body %></p>
      </div>
    <% end %>
  </div>

<% end %>



  <% if !current_user.mentor? && @user.mentor? %>
    <%= button_to mentorship_requests_path(mentor_id: @user.id, mentee_id: current_user.id), method: :post, class: 'mentorship_request_button' do %>
      Solicitar Mentoria
    <% end %>
  <% end %>

  <%= link_to :back, class: "x_button" do %>
    <%= image_tag "close.png", alt: "X", class: "x_button_image" %>
  <% end %>
</div>