config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :mentorship_requests, only: %i[new create index show update destroy] do
    member do
      patch 'accept', to: 'mentorship_requests#accept', as: 'accept_mentorship_request'
      delete 'destroy', to: 'mentorship_requests#destroy', as: 'destroy_mentorship_request'
      patch 'cancel', to: 'mentorship_requests#cancel', as: 'cancel_mentorship_request'

    end
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new', as: 'new_user_session'
    post 'sign_in', to: 'users/sessions#create', as: 'user_session'
    delete 'sign_out', to: 'users/sessions#destroy', as: 'destroy_user_session'
  end

  root to: 'pages#search'
  get '/search', to: 'pages#search', as: 'search'
  get '/profile', to: 'pages#profile'

  get 'users/:id', to: 'users#show', as: 'user'
  get '/matches', to: 'pages#matches', as: 'matches'
  patch '/mentorship_requests/:id/accept', to: 'mentorship_requests#accept', as: 'accept_mentorship_request'
  patch '/mentorship_requests/:id/destroy', to: 'mentorship_requests#destroy', as: 'destroy_mentorship_request'
  patch '/mentorship_requests/:id/cancel', to: 'mentorship_requests#cancel', as: 'cancel_mentorship_request'


  # Updated users resource to include edit and update actions
  resources :users, only: %i[show edit update]

  resources :posts, only: [:new, :create, :edit, :update, :destroy]
  resources :badges, only: [:show]
end

app/views/shared/_request_status.html.erb
<% if request.status == 'accepted' %>
  <div>
    <%= image_tag 'tick.png', alt: 'Accepted', class: 'status-icon' %>
  </div>
<div>
  <% if current_user.mentor? %>
    <%= link_to user_path(request.mentee), class: 'x_button' do %>
      <%= image_tag "info_logo.png", alt: "Info", class: "matches-x-button" %>
    <% end %>
  <% else %>
    <%= link_to user_path(request.mentor), class: 'x_button' do %>
      <%= image_tag "info_logo.png", alt: "Info", class: "matches-x-button" %>
    <% end %>
  <% end %>
</div>
  <% if request.chatroom.present? %>
    <div>
      <%= link_to chatroom_path(request.chatroom), class: 'x_button' do %>
        <%= image_tag 'message.png', alt: 'msg', class: 'matches-x-button' %>
      <% end %>
    </div>
  <% else %>
    <div>
      <!-- Handle the case where there is no chatroom -->
    </div>
  <% end %>

  <div>
    <%= button_to destroy_mentorship_request_path(request), method: :patch, class: 'x_button', form: { data: { turbo_confirm: 'De certeza que queres apagar esta conversa? Esta acção não é reversível!' } } do %>
      <%= image_tag 'close.png', alt: 'Cancel', class: 'matches-x-button' %>
    <% end %>
  </div>

<% else %>
  <div>
    <%= button_to cancel_mentorship_request_path(request), method: :patch, class: 'x_button', form: { data: { turbo_confirm: 'De certeza que queres apagar esta conversa? Esta acção não é reversível!' } } do %>
      <%= image_tag 'close.png', alt: 'Cancel', class: 'matches-x-button' %>
    <% end %>
  </div>

<% end %>
<% if current_user.mentor? && request.status != 'accepted' %>
  <div>
    <%= button_to accept_mentorship_request_path(request), method: :patch, class: 'yes_button' do %>
      Sim
    <% end %>
    <%= button_to cancel_mentorship_request_path(id: request.id), method: :patch, class: 'no_button' do %>
      Não
    <% end %>
  </div>
<% end %>