config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :mentorship_requests, only: %i[new create index show update destroy] do
    member do
      patch 'accept', to: 'mentorship_requests#accept', as: 'accept_mentorship_request'
      delete 'destroy', to: 'mentorship_requests#destroy', as: 'destroy_mentorship_request'
      patch 'cancel', to: 'mentorship_requests#cancel', as: 'cancel_mentorship_request'

    end
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new', as: 'new_user_session'
    post 'sign_in', to: 'users/sessions#create', as: 'user_session'
    delete 'sign_out', to: 'users/sessions#destroy', as: 'destroy_user_session'
  end

  root to: 'pages#search'
  get '/search', to: 'pages#search', as: 'search'
  get '/profile', to: 'pages#profile'

  get 'users/:id', to: 'users#show', as: 'user'
  get '/matches', to: 'pages#matches', as: 'matches'
  patch '/mentorship_requests/:id/accept', to: 'mentorship_requests#accept', as: 'accept_mentorship_request'
  patch '/mentorship_requests/:id/destroy', to: 'mentorship_requests#destroy', as: 'destroy_mentorship_request'
  patch '/mentorship_requests/:id/cancel', to: 'mentorship_requests#cancel', as: 'cancel_mentorship_request'


  # Updated users resource to include edit and update actions
  resources :users, only: %i[show edit update]

  resources :posts, only: [:new, :create, :edit, :update, :destroy]
  resources :badges, only: [:show]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :page_title %> - BuddyIsecApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "chatrooms", "login", "matches", "mentors", "navbar", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="container">
        <%= image_tag 'campus_buddy_logo_black.png', class: 'logo' %>
        <h1 class="page-title"><%= yield :page_title %></h1>
      </div>
    </header>
    <div class="container">
      <div class="main-content">
        <%= yield %>
      </div>
    </div>

    <% if current_user.present? %>
      <footer class="navbar navbar-expand-lg navbar-dark bg-dark fixed-bottom">
        <div class="container container-fluid justify-content-center">
          <%# if current_user %>
          <div class="">
            <%= link_to matches_path, class: "btn btn-outline-light mx-2 navbar-button" do %>
              <%= image_tag "matches-logo.png", alt: "Matches", class: "navbar-logo" %>
            <% end %>
          </div>
          <div class="line"></div>
          <div class="">
            <%= link_to search_path, class: "btn btn-outline-light mx-2 navbar-button" do %>
              <%= image_tag "search-logo.png", alt: "Search", class: "navbar-logo" %>
            <% end %>
          </div>
          <div class="line"></div>
          <div>
            <%= link_to profile_path, class: "btn btn-outline-light mx-2 navbar-button" do %>
              <%= image_tag "profile-logo.png", alt: "Profile", class: "navbar-logo" %>
            <% end %>
          </div>
        </div>
      </footer>
    <% end %>
  </body>
</html>